---------------------------------------------------------------------------------------------
-- Copyright (c) 2025 Ayios. All rights reserved.
-- All code within this repository created by Ayios is under MIT license. Other code within
-- this repository is under its own respective license which will be displayed within their
-- respective files or around the areas of their code.
-- See LICENSE in the project root for license information.
---------------------------------------------------------------------------------------------

-- This file contains a list of user IDs of authorized users.
-- This system is set up to let you *immediately* test Ayios systems.
-- You are responsible for a robust permission system.
return {
    125196014,
    game.CreatorId,
    -- The next Roblox User ID here
}